### ISSUE TITLE
Matting laplacian.py error

### ISSUE THREAD

**Issue by martinbenson** [martinbenson/deep-photo-styletransfer#1]
Code fails (instead of just nagging) on newer numpy releases - need to cast tlen to int

**Comment by themightyoarfish** [comment]
To be precise, the error is
```
$ python3 mattinglaplacian.py --dir=../examples/input/ --out=.
Traceback (most recent call last):
  File "mattinglaplacian.py", line 87, in <module>
    CSR = getlaplacian1(img, np.zeros(shape=(h, w)), 1e-7, 1)
  File "mattinglaplacian.py", line 20, in getlaplacian1
    row_inds = np.zeros(tlen)
TypeError: 'numpy.float64' object cannot be interpreted as an integer
```
