### ISSUE TITLE
Python 'join' TypeError in mattinglaplacian.py 

### ISSUE THREAD

**Issue by Multiboxer** [martinbenson/deep-photo-styletransfer#5]
Fresh install of python3 with all requirements gives this error in mattinglaplacian.py,

% python3 mattinglaplacian.py 
Traceback (most recent call last):
`  `File "mattinglaplacian.py", line 82, in <module>
`  ` `  `for filename in glob.iglob(os.path.join(args.directory, '*.png')):
`  `File "/usr/lib/python3.5/posixpath.py", line 89, in join
`  ` `  `genericpath._check_arg_types('join', a, *p)
`  `File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
`  ` `  `(funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'

**Comment by Multiboxer** [comment]
Ah, this was my bad I had assumed the directory was automatically detected and did not read the instructions correctly.
